#!/bin/bash

set -e

if [ -d /boot/efi/EFI/refind/themes/hamonikr ] ; then
    rm -rf /boot/efi/EFI/refind/themes/hamonikr
fi

if [ -d /boot/efi/EFI/refind/icons ] ; then
    rm -rf /boot/efi/EFI/refind/icons
fi

#DEBHELPER#
