#!/bin/bash

set -e

if [ -d /etc/refind.d ] ; then
    rm -rf /etc/refind.d
fi

if [ -d /boot/efi/EFI/refind/themes/hamonikr ] ; then
    rm -rf /boot/efi/EFI/refind/themes/hamonikr
fi

if [ -d /boot/efi/EFI/refind/icons ] ; then
    rm -rf /boot/efi/EFI/refind/icons
fi

if [ -d /boot/efi/EFI/refind ] ; then
    rm -rf /boot/efi/EFI/refind
fi

#DEBHELPER#
